# Generated by Django 4.1.7 on 2023-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atracoes", "0001_initial"),
        ("core", "0002_alter_pontoturistico_aprovado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="atracao",
            field=models.ManyToManyField(to="atracoes.atracao"),
        ),
    ]
