# Generated by Django 4.1.7 on 2023-02-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("comentarios", "0001_initial"),
        ("core", "0003_pontoturistico_atracao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pontoturistico", old_name="atracao", new_name="atracoes",
        ),
        migrations.AddField(
            model_name="pontoturistico",
            name="avaliacoes",
            field=models.ManyToManyField(to="avaliacoes.avaliacao"),
        ),
        migrations.AddField(
            model_name="pontoturistico",
            name="comentarios",
            field=models.ManyToManyField(to="comentarios.comentario"),
        ),
    ]
