# Generated by Django 4.1.7 on 2023-02-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
        ("core", "0004_rename_atracao_pontoturistico_atracoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="endereco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="enderecos.endereco",
            ),
            preserve_default=False,
        ),
    ]
