# Generated by Django 4.1.7 on 2023-02-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
        ("core", "0005_pontoturistico_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pontoturistico",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enderecos.endereco",
            ),
        ),
    ]
